"English":
- 'src/en/**'

"Russian":
- 'src/ru/**'

"Ukrainian":
- 'src/ua/**'

"Scripts":
- 'scripts/**'

"Design":
- changed-files:
  - any-glob-to-any-file: '**/proposals/**'
  - 'src/en/general-proposals/**'
