name: Test mdBook Build & Upload Artifact

on:
  # Run on only PR, no gh pages stuff
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
      - name: Install mdbook-spacewizards
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab a specific tag with caching
          repo: space-wizards/mdBook-spacewizards
          tag: v0.4.35
          cache: enable
      - name: Install plugins
        uses: taiki-e/install-action@v2.18.6
        with:
          tool: mdbook-admonish@1.11.1,mdbook-linkcheck@0.7.7,mdbook-mermaid@0.12.6,mdbook-template@1.1.0,mdbook-emojicodes@0.3.0
      - name: Build with mdBook
        run: mdbook build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Built Site
          path: ./book/html
          retention-days: 3